docs/source/conf.py, src/mlte/properties/cpu/local_process_cpu_utilization.py, src/mlte/properties/memory/local_process_memory_consumption.py, src/mlte/properties/property.py, src/mlte/properties/storage/local_model_size.py, tox.ini
Resolves #15.
This PR refactors the property evaluation API. Specifically, it introduces the syntax `property.evaluate()` in conjunction with the standard overload of the `__call__()` method for properties.
Furthermore, this PR introduces an additional level of indirection that will be necessary when we generate reports from collections of properties. Each property must now implement an `_evaluate()` method that returns the "raw" result of the property. We combine this with a static `_semantics()` method to recover the semantics of the property output in `evaluate()`.
Finally, this PR standardizes the interface for properties with the help of a metaclass attached to the `Property` base.
=> Refactor Property Evaluation API

docs/source/conf.py, src/mlte/properties/__init__.py, src/mlte/properties/cpu/local_process_cpu_utilization.py, src/mlte/properties/memory/local_process_memory_consumption.py, src/mlte/properties/property.py, src/mlte/properties/property_token.py, src/mlte/properties/result/__init__.py, src/mlte/properties/result/evalution_result.py, src/mlte/properties/result/integer.py, src/mlte/properties/result/opaque.py, src/mlte/properties/storage/local_model_size.py, test/properties/cpu/test_local_process_cpu_utilization.py, test/properties/memory/test_local_process_memory_consumption.py, test/properties/storage/test_local_model_size.py, test/properties/test_property_token.py, testbed/main.py, testbed/resolver.py
This PR refactors the property evaluation API (again).
The refactor focuses on simplifying the process of authoring custom properties. Specifically, users of the package need only implement a single method, `__call__()`, in order to create a fully-functional property. In addition to this, we provide the _option_ of providing a `semantics()` method to interpret the result of property execution. If `semantics()` is not provided, we supply a default implementation of `EvaluationResult` that simply wraps the raw data produced by the property.
Furthermore, this PR introduces functionality to 'link' an `EvaluationResult` with the property that produced it. This is a necessary step for implementing Suites.
=> Property Evaluation API

src/mlte/measurement/measurement.py, src/mlte/measurement/validation/validation_result.py, test/measurement/cpu/test_local_process_cpu_utilization.py, test/measurement/memory/test_local_process_memory_consumption.py
Resolves #37.
This PR makes the `EvaluationResult` used by a `Validator` to produce a `ValidationResult` available in the `ValidationResult` instance. This is important because it allows the "raw" results to be read from the top level during report generation and used for other purposes, such as upload to an experiment tracking service.
=> Include `EvaluationResult` in `ValidationResult`

src/mlte/measurement/evaluation/__init__.py, src/mlte/measurement/evaluation/integer.py, src/mlte/measurement/evaluation/opaque.py, src/mlte/measurement/evaluation/real.py, test/measurement/test_evaluation.py
Resolves #29.
Resolves #30.
This PR introduces the following changes:
- Add a `Real` type for `EvaluationResult`
- Increase the functionality of `Opaque` to make it subscriptable
- Add tests for `Opaque`, `Integer` and `Real`
=> Add `Real` Type

src/mlte/report/report.py, test/schema/test_report_schema.py, testbed/main.py
This PR simply refactors `artifacts_url` to `artifact_url` within the `Report` functionality. A name change.
Resolves #45.
=> Refactor `artifacts_url` to `artifact_url`

docs/source/examples.md, docs/source/glossary.md, docs/source/quickstart.md, src/mlte/_private/schema.py, src/mlte/report/report.py, src/mlte/schema/report/v0.0.1/schema.json, src/mlte/schema/spec/v0.0.1/schema.json, src/mlte/spec/__init__.py, src/mlte/spec/spec.py, src/mlte/suite/__init__.py, test/schema/test_report_schema.py, test/schema/test_suite_schema.py, test/spec/test_spec.py, testbed/main.py
This PR accomplishes our terminology change from "suite" to "specification" to describe the mechanism that organizes properties into a coherent document. Within the `mlte` implementation, this entails refactoring the `Suite` type to the `Spec` type. This type is used in a wide variety of locations throughout the codebase, so this PR has a relatively-large blast radius. However, the functionality remains exactly the same (for now).
Resolves #59.
=> Refactor `Suite` to `Spec`

.gitignore, demo/confusion_matrix.py, demo/evidence.ipynb, src/mlte/_global/state.py, src/mlte/binding/binding.py, src/mlte/measurement/__init__.py, src/mlte/measurement/cpu/local_process_cpu_utilization.py, src/mlte/measurement/external_measurement.py, src/mlte/measurement/memory/local_process_memory_consumption.py, src/mlte/measurement/result/result.py, src/mlte/spec/bound_spec.py, src/mlte/spec/spec.py, src/mlte/store/api/local/api.py, test/measurement/result/test_image.py, test/measurement/result/test_integer.py, test/measurement/result/test_opaque.py, test/measurement/result/test_real.py, test/measurement/test_external_measurement.py, test/schema/test_boundspec_schema.py, test/schema/test_result_schema.py, test/spec/test_boundspec.py, test/spec/test_spec.py
* Fixes #128 by centralizing check() call as a method of GlobalState
* Fixes #127, refactored to have 1 common read/write artifact internal local api function.
* Fixes #117, making Identifier and MeasurementMetadata internal, adapting imports in tests, internal modules, and extended results to now load them from internal modules. 
* As part of #117, added ExternalMeasurement collect_data() method to create a result of a certain type when there is no function to call/evaluate. In practice, it currently the same as ExternalMeasurement's evaluate(), but it could differ in the future if evaluate() starts really executing the function it is measuring. The main goal of this method is to give the library user a clearer way to indicate it is just wrapping data in the result type provided to the …
=> Refactoring and external results

src/mlte/property/costs/storage_cost.py, src/mlte/property/costs/training_compute_cost.py, src/mlte/property/costs/training_memory_cost.py, src/mlte/property/functionality/task_efficacy.py, src/mlte/property/property.py
Two minor changes:
- __repr__ was moved to the base Property class, since it works there anyway, so creating a new Property does not require one to duplicate that function.
- When loading a Property from a JSON file, removed hardcoded list of subpackages containing properties, and changed to use reflection to find all subpackages containing properties, to simplify the addition of properties in new subpackages.
=> Simplifying addition of new properties

README.md
Resolves issue #174
@turingcompl33t, a note - it appears that the conference version of our paper is not posted publicly anywhere online, so I cited the arXiv version. We may want to change that at some point.
Please check the language I used to describe MLTE, because I updated it from 'toolkit'. 
Also, hilarious that you used cleverHans as an example because before I put that comment into the doc, I checked their repository to see if I had remembered correctly that they cited their paper. It's a great example.
=> Add paper to README.md

Makefile, src/mlte/artifact/artifact.py, src/mlte/negotiation/negotiation_card.py, src/mlte/session/state.py, src/mlte/store/__init__.py, src/mlte/store/base.py, src/mlte/store/factory.py, src/mlte/store/underlying/fs.py, src/mlte/store/underlying/http.py, src/mlte/store/underlying/memory.py, src/mlte/store/util.py, src/mlte/web/store/api/dependencies.py, src/mlte/web/store/api/endpoints/artifact.py, src/mlte/web/store/api/model.py, src/mlte/web/store/main.py, src/mlte/web/store/state/state.py, test/negotiation/test_negotiation_card.py, test/store/fixture.py, test/store/test_underlying.py, test/web/store/test_artifact.py
Resolves #195.
This PR adds the ability to implicitly create organizational elements on write to the artifact store. Three distinct interfaces have been updated:
- The `Store` interface now supports an optional parameter, `parents`, to `write_artifact`, that specifies that organizational elements should be created if they do not exist
- The web API endpoint for artifact write operations has been modified to support specifying `parents` in the request
- The artifact protocol base type, `Artifact`, now supports `parents` in `Artifact.save()` and `Artifact.save_with()`
Ultimately, this means that we can now write code like the following:
```python
card = NegotiationCard("my-card")
card.save(parents=True)
```
And the write will succeed, even when the namespace, model, and version were not …
=> Support Implicit Creation of Organizational Elements on Artifact Write

Makefile, mlte/_private/meta.py, mlte/artifact/artifact.py, mlte/measurement/measurement.py, mlte/property/property.py, mlte/validation/result.py, mlte/value/artifact.py, mlte/value/base.py, test/value/test_extension.py
Resolves #202.
In addition, it adds a unit test for `mlte.value.base.Value` to ensure that custom implementations that do not meet the interface cannot be instantiated.
=> Unify the Implementation of Metaclass Functions

demo/confusion_matrix.py, demo/evidence.ipynb, demo/report.ipynb, demo/requirements.ipynb, mlte/measurement/external_measurement.py, mlte/value/base.py, test/measurement/test_external_measurement.py, test/value/test_extension.py
Resolves #203.
This PR refactors `mlte.value.base.Value` to `mlte.value.base.ValueBase`. The name is changed, and the type is made a subclass of `mlte.value.artifact.Value`. This simplifies the implementation of other features (like `ExternalMeasurement`). 
Note that this is what @sebastian-echeverria urged me to do in the first place. I failed to see the utility then, but in the process of fixing the demo functionality that I broke, it became clear.
=> Refactor `mlte.value.base.Value` and Fix Demonstration

mlte/model/base_model.py, mlte/store/underlying/fs.py, mlte/store/underlying/http.py, test/store/test_query.py, test/web/store/context/test_model.py, test/web/store/context/test_namespace.py, test/web/store/context/test_version.py, test/web/store/test_artifact.py
Resolves #212.
`pydantic.BaseModel.dict()` is deprecated. These calls are refactored to `pydantic.BaseModel.model_dump()`.
=> Refactor Calls to Deprecated `BaseModel.dict()`

mlte/artifact/artifact.py, mlte/store/base.py, mlte/store/underlying/fs.py, mlte/store/underlying/http.py, mlte/store/underlying/memory.py, mlte/web/store/api/endpoints/artifact.py, mlte/web/store/api/model.py, test/negotiation/test_artifact.py, test/store/test_underlying.py, test/web/store/test_artifact.py
- Resolves #171 
- Resolves #178 
We determined that the current way forward with artifact versioning and write semantics is as follows:
- By default, attempts to overwrite existing artifacts fail with `ErrorAlreadyExists`
- Clients can opt-in to overwrite behavior with the use of optional parameters in MLTE clients
This behavior is important for interactions in the web UI. Here, users will be interested in iterative development of the content in specific artifacts, like the negotiation card and the report. We don't want users to have to create a new version of the artifact every time they enter some new text and hit "save." Therefore, the frontend will implicitly use this overwrite functionality when an existing artifact is edited.
This functionality is exposed by the artifact protocol. …
=> Implement Versioning Semantics for Artifact Store

mlte/cli/cli.py, mlte/web/store/app_factory.py, mlte/web/store/core/config.py, mlte/web/store/main.py
- Resolves #244 
This PR adds a configuration option to the artifact store to accept allowed CORS origins. The configuration is specified via the commandline:
```bash
mlte store --allowed-origins http://localhost:9000
```
or via the environment:
```bash
ALLOWED_ORIGINS='["http://localhost:9000"]' mlte store
```
=> Add CORS Configuration Option to Artifact Store

demo/confusion_matrix.py, demo/evidence.ipynb, demo/report.ipynb, mlte/_private/schema.py, mlte/measurement/cpu/local_process_cpu_utilization.py, mlte/measurement/memory/local_process_memory_consumption.py, mlte/value/types/integer.py, test/measurement/cpu/test_local_process_cpu_utilization.py, test/measurement/memory/test_local_process_memory_consumption.py, test/schema/test_spec_schema.py, test/schema/test_validatedspec_schema.py, test/schema/test_value_schema.py
Mostly addresses #233, but also made some other fixes:
- Addresses #233 by making CPUStatistics and MemoryStatistics derive from ValueBase,  as well as fixed and re-enabled unit tests for these value types.
- Fixed and re-enabled schema unit tests for Spec, ValidatedSpec and Value schemas.
- Fixed demo, ensuring evidence and report notebooks work properly with new version of objects (except for report generation), and fixed bug in ConfusionMatrix which was not properly serializing a numpy array.
=> Fixed CPUStatistics and MemoryStatistics, demo, and schema tests

mlte/artifact/model.py, mlte/artifact/type.py, mlte/frontend/nuxt-app/assets/schema/artifact/negotiation/v0.0.1/schema.json, mlte/frontend/nuxt-app/assets/schema/artifact/report/v0.0.1/schema.json, mlte/frontend/nuxt-app/assets/schema/artifact/spec/v0.0.1/schema.json, mlte/frontend/nuxt-app/assets/schema/artifact/validated/v0.0.1/schema.json, mlte/frontend/nuxt-app/assets/schema/artifact/value/v0.0.1/schema.json, mlte/schema/artifact/negotiation/v0.0.1/schema.json, mlte/schema/artifact/report/v0.0.1/schema.json, mlte/schema/artifact/spec/v0.0.1/schema.json, mlte/schema/artifact/validated/v0.0.1/schema.json, mlte/schema/artifact/value/v0.0.1/schema.json, mlte/value/model.py, testbed/main.py, testbed/resolver.py
This PR refactors enum serialization for MLTE artifacts.
Previously, I had used `auto` to automatically generate the value of the `enum`. However, without the `StrEnum` type, this feature is only capable of generating integers for the `enum` value, making it difficult to recover the `enum` from the serialized representation.
To fix this, I just removed use of `auto` and inserted explicit strings manually for the enumerations.
=> Refactor Enum Serialization

mlte/frontend/nuxt-app/pages/index.vue, mlte/frontend/nuxt-app/pages/report.vue
- Resolves #179
This PR adds the ability to render MLTE reports in the web UI.
=> Report Rendering

docs/docs/qa_scenario.md
Just fixing some typos in the name of the folder for the scenarios demo in the documentation.
=> Typos in scenarios demo how-to folder paths

.bumpversion.cfg, .gitignore, README.md, docs/docs/development.md, docs/docs/index.md, pyproject.toml
Publish the package using MacOS; addresses issue with poetry build calling on a version of python that did not exist in the file system.
Updated the development docs to account for this issue.
New package version includes several new UI features!
=> Publish using MacOS

mlte/frontend/nuxt-app/pages/index.vue
Addresses #361 
Second attempt at fixing the timestamp display in the homepage table. All timestamps are now generated in the backend so they are consistently passed to the frontend in the same way and can be displayed correctly.
=> Fix timestamp display

README.md, docs/docs/negotiation_card.md, docs/mkdocs.yml
Adds the MLTE negotiation card into the documentation as a reference.
Updated the paper version from arXiv to IEEE in our README, and updated all README links so that they now open in another tab (which is our default for the documentation).
=> Add Negotiation Card to Docs, Update README

mlte/session/state.py, test/session/test_session.py
Added optional functionality to eagerly create structural parent elements (model/version) for a context when using the MLTE library, either by calling a method or setting a param when setting the context. Addresses #335 .
=> Eager Structural Parent Elements Creation

.bumpversion.cfg, .gitignore, README.md, docs/docs/development.md, docs/docs/getting_started.md, docs/docs/index.md, mlte/backend/core/config.py, mlte/cli/.env, mlte/cli/.gitignore, mlte/cli/cli.py, mlte/frontend/nuxt-app/package.json, pyproject.toml
Publishes MLTE 0.2.9 (already uploaded to PyPi).
- Updated version number
- Added --version flag to CLI to show the current version
- Made localhost:8000 a default allowed-origin to simplify running of deployed frontend and backend
- Updated getting_started doc with clearer instructions to run backend and frontend
- Removed uneeded step in development doc for publishing
=> Publish MLTE 0.2.9

.github/workflows/ci.yaml, .readthedocs.yaml, Makefile, docs/docs/development.md, mlte/store/catalog/catalog_group.py, mlte/store/catalog/sample_catalog.py, poetry.lock, pyproject.toml
- Fixes bug that prevented doc generation (#485)
- Addresses #484 by integrating doc generation in CI process, to detect and fix issues earlier in the process
- Fixes issue with Readthedocs integration after dependencies were moved to pyproject file in Test Catalog PR (#486)
=> Document Generation Fixes

.bumpversion.cfg, README.md, docs/docs/index.md, mlte/frontend/nuxt-app/package.json, pyproject.toml
Since we are starting work on major architectural changes, it would be good to create, tag and publish a small increment version to 1.0.0 that add the couple of improvements we have been working over the last few weeks. 
This specific PR just updates the version number to 1.0.1 so we can create a release and publish it with the proper version.
Btw, the fixes that this version will have once we create the release, which are currently in master but not in 1.0.0, include:
- Fixes for the Frontend to properly work in a remotely deployed dockerized server (#405 and #418)
- Bug fixes for creating docker image from Frontend
- Fixes in configuration for readme to properly show up in PyPi website as the package description (#491)
- Fixes in documentation to avoid inconsistencies in examples …
=> Updating version to 1.0.1

poetry.lock, pyproject.toml
Addresses #550 by explicitly allowing all 3.11.x versions to work with MLTE in the pyproject restrictions.
=> Bug/python 3.11.x ci support

.dockerignore, .github/workflows/ci.yaml, Makefile, demo/scenarios/demo_script.txt, demo/scenarios/get_model.sh, docker/Dockerfile.backend, docker/Dockerfile.frontend, docker/Dockerfile.mlte, docker/Dockerfile.python, docker/build.sh, docs/docs/development.md, mlte/backend/core/config.py, mlte/backend/main.py, mlte/frontend/nuxt-app/.gitignore, mlte/frontend/nuxt-app/components/TestCatalog/entry-edit.vue, mlte/frontend/nuxt-app/package-lock.json, pyproject.toml
Contains a series of improvements for the live demo, as well as fixes for versions that have changed and were not pinned.
- Addresses #559 by updating demo readme to include more detailed informations on how to run demo, updating the dev doc to clarify and separate some setup steps, and using curl instead of wget in getting model for better compatibility
- Addresses #557, by changing docs to remove use of removed "poetry shell" and explicitly creating venv, and adding workaround to package information to avoid "format" error
- Addresses #561 by pinning JS frontend dependencies by adding package-lock.json to git and docker images
- Addresses #560 by explicitly adding readme to docker image before building MLTE package (readme is now a dependency)
- Addresses #558 by making make commands …
=> Demo and versioning fixes

demo/simple/confusion_matrix.py, mlte/validation/validator.py, test/validation/test_validator.py
Validator: fixed bug where messages set to generated Results when valdating were not properly serializing Values, turning them into JSON instead of getting their internal values. Addresses #599. Now args are turned to strings before the arrays are dumped to JSON, letting a Value properly be converted to its string represenatation.
=> Fixes Bug Printing Values to Result Messages in Validator

README.md, docs/docs/using_mlte.md, mlte/session/session.py, mlte/session/session_stores.py, mlte/store/custom_list/factory.py, test/session/test_session.py, test/validation/test_test_suite_validator.py
Resolves #720. More specifically: 
- For the optional env vars that can be used to set up context/store when using the MLTE as a package/library, unified all store related vars into one, MLTE_STORE_URI, as all the rest of the codebase assumes all stores use the same URI for all stores (except possibly for the catalog, if additional ones are configured). Now this is consistent with how store URIs are used internally.
- Also moved this env handling to the Session class, at the same level as the context (model/version) env handling, since these env vars are targeted to the library use, not the backend (which has separate vars set for Docker).
=> Fixes Consistency of URI Env Var Use
