- README.md
- src/mlte/properties/cpu/__init__.py
- src/mlte/properties/cpu/local_process_cpu_utilization.py
- test/properties/cpu/test_local_process_cpu_utilization.py
Resolves [#5](https://github.com/turingcompl33t/mlte/issues/5).
> Refactor ProcessLocalCPUUtilization to LocalProcessCPUUtilization

- src/mlte/properties/memory/__init__.py
- src/mlte/properties/memory/local_process_memory_consumption.py
- test/properties/memory/test_local_process_memory_consumption.py
> Rename ProcessLocalMemoryConsumption to LocalProcessMemoryConsumption

- test/properties/storage/test_local_model_size.py
> Add tests for LocalModeSize property

- Makefile
- src/mlte/measurement/cpu/local_process_cpu_utilization.py
- src/mlte/measurement/measurement.py
- src/mlte/measurement/memory/local_process_memory_consumption.py
- src/mlte/measurement/storage/local_object_size.py
- src/mlte/measurement/validation/validation_result.py
- src/mlte/properties/__init__.py
- src/mlte/properties/costs/__init__.py
- src/mlte/properties/costs/storage_cost.py
- src/mlte/properties/costs/training_compute_cost.py
- src/mlte/properties/costs/training_memory_cost.py
- src/mlte/properties/property.py
- src/mlte/suites/__init__.py
- src/mlte/suites/suite.py
- test/measurement/storage/test_local_object_size.py
- test/measurement/test_measurement.py
- test/properties/test_property.py
- testbed/main.py
- testbed/resolver.py
Resolves #14.
This PR integrates prior work on `Measurement` with both `Property`s and `Suite`s.
> Properties and Suites

- .bumpversion.cfg
- docs/source/conf.py
- setup.cfg
- src/mlte/measurement/cpu/local_process_cpu_utilization.py
- src/mlte/measurement/memory/local_process_memory_consumption.py
> Hide Output from Internal Subprocesses

- .bumpversion.cfg
- docs/source/conf.py
- setup.cfg
- src/mlte/measurement/memory/local_process_memory_consumption.py
- src/mlte/report/report.py
- testbed/main.py
> Update Type for Average in `LocalProcessMemoryConsumption`

- demo/evidence.ipynb
- demo/report.ipynb
- demo/requirements.ipynb
- demo/requirements.txt
- requirements_dev.txt
Minor fixes mainly to demo code:
- Adding code to automatically create folders used during the demo in case they don't already exist in the code where the demo is being run.
- Added a requirements file with the libraries needed to un the the demo sample notebook.
- Updated once dependency from the main requirements_dev file, since it was not working properly with the rest and it was giving an out of date error (importlib-metadata).
> Demo fixes

- src/mlte/measurement/validation/validation_result.py
- src/mlte/measurement/validation/validator.py
> Embed Validator Name in `ValidationResult` Instance

- .github/workflows/ci.yaml
- README.md
- test/measurement/memory/test_local_process_memory_consumption.py
This PR completes the addition of support for OSX by adding checks in the required locations in unit tests.
@sebastian-echeverria added the preliminary features required for this PR in a separate (merged) PR.
> Explicit Checks for OSX

- .github/workflows/ci.yaml
- requirements_dev.in
- requirements_dev_3.10.txt
- requirements_dev_3.8.txt
- requirements_dev_3.9.txt
- setup.cfg
- src/mlte/schema/artifact/negotiation/v0.0.1/schema.json
- src/mlte/store/query.py
- src/mlte/web/store/core/config.py
- test/store/fixture.py
- test/store/test_underlying.py
- tools/schema.py
Resolves #192.
@sei-aderr pointed out a bug that was preventing the artifact store from executing from the CLI. The root cause was that I had failed to make the `web` and `store` subdirectories proper Python sub-packages. This PR addresses that issue.
Along the way, I encountered some outdated dependency errors that required updates. I addressed these as well because I could not fix the CLI without resolving some dependency issues.
> CLI Bugfix

- mlte/artifact/artifact.py
- mlte/negotiation/negotiation_card.py
- test/artifact/test_artifact.py
- test/fixture/artifact.py
- test/fixture/store.py
> Address Bad Updates from Merge

- .readthedocs.yaml
- README.md
- docs/mkdocs.yml
- docs/tools/generate_ref_pages.py
> Update Documentation Publication Configuration

- mlte/store/query.py
- mlte/value/model.py
> Remove Calls to Deprecated `update_forward_refs()`

- mlte/store/underlying/fs.py
- test/store/test_underlying.py
> Report Relative Paths on List Operations for Filesystem Store Backend

- mlte/frontend/README.md
- mlte/frontend/nuxt-app/.eslintrc.json
- mlte/frontend/nuxt-app/components/scrollable-list-item.vue
- mlte/frontend/nuxt-app/nuxt.config.ts
- mlte/frontend/nuxt-app/package-lock.json
- mlte/frontend/nuxt-app/pages/index.vue
- mlte/frontend/nuxt-app/pages/negotiation-card.vue
Addresses #184, partially addresses #185, #186. Able to read and display versions + models but not add new ones through the UI
> Initial API Endpoint Integration

- mlte/spec/spec.py
- mlte/validation/validated_spec.py
- Fixes #271, spec id not being stored for validated spec, and equalities that should have checked that as well.
> Fixes missing Spec id in stored ValidatedSpec

- mlte/frontend/README.md
- mlte/frontend/nuxt-app/.eslintrc.json
- mlte/frontend/nuxt-app/composables/artifact-validation.ts
- mlte/frontend/nuxt-app/composables/error-handling.ts
- mlte/frontend/nuxt-app/layouts/base-layout.vue
- mlte/frontend/nuxt-app/pages/index.vue
- mlte/frontend/nuxt-app/pages/negotiation-card.vue
- mlte/frontend/nuxt-app/pages/report.vue
- mlte/frontend/nuxt-app/pages/todo.vue
- Resolves #286 
- Resolves #285 
- Resolves #282 
- Resolves #281 
This PR refactors the implementation of the index page in the MLTE UI to remove support for multi-select of models and versions and add support for single-select alone. In addition, it makes some small UI tweaks, and applies linting and formatting to the frontend source.
> UI Updates

- .bumpversion.cfg
- docs/docs/development.md
- docs/docs/index.md
- poetry.lock
- pyproject.toml
This PR makes some tweaks to the package to prepare it for publication.
> Package Publication

- .bumpversion.cfg
- .gitignore
- README.md
- docs/docs/index.md
- pyproject.toml
> Publish 0.2.3

- mlte/web/store/main.py
- mlte/web/store/util/origins.py
- test/web/store/test_util_origin.py
- testbed/store/ns/IrisClassifier/0.0.1/default.report.json
This PR introduces a minor bugfix for origin resolution on MLTE API startup.
> API Origin Fix

- .bumpversion.cfg
- README.md
- docs/docs/index.md
- pyproject.toml
This PR publishes `mlte` 0.2.4.
> Publish 0.2.4

- .bumpversion.cfg
- README.md
- docs/docs/index.md
- pyproject.toml
This PR publishes `mlte` 0.2.5.
> Publish mlte 0.2.5

- .bumpversion.cfg
- docs/docs/index.md
- pyproject.toml
This PR publishes MLTE `0.2.6`.
> Publish 0.2.6

- mlte/frontend/nuxt-app/pages/index.vue
Addresses #340
Tested with a couple models and versions and everything was saving properly, did not mess with namespaces too much due to their pending removal.
> Add cookie for model and version selection

- .bumpversion.cfg
- README.md
- docs/docs/index.md
- mlte/frontend/nuxt-app/package.json
- pyproject.toml
> Publish MLTE 0.2.8

- mlte/frontend/nuxt-app/layouts/base-layout.vue
- mlte/frontend/nuxt-app/pages/export-report.vue
- mlte/frontend/nuxt-app/pages/index.vue
Initial version of the report export.
> Report Export

- .bumpversion.cfg
- README.md
- docs/docs/index.md
- mlte/frontend/nuxt-app/package.json
- pyproject.toml
Just bumping version number to release new package to PyPi.
> Publish MLTE 0.2.10

- mlte/frontend/nuxt-app/components/Admin/user-edit.vue
- mlte/frontend/nuxt-app/layouts/base-layout.vue
- mlte/frontend/nuxt-app/pages/admin/group-management.vue
- mlte/frontend/nuxt-app/pages/admin/user-management.vue
- mlte/frontend/nuxt-app/pages/index.vue
- mlte/frontend/nuxt-app/pages/login.vue
- mlte/frontend/nuxt-app/pages/negotiation-card.vue
- mlte/frontend/nuxt-app/pages/regular/profile-edit.vue
- mlte/frontend/nuxt-app/pages/report-export.vue
- mlte/frontend/nuxt-app/pages/report-form.vue
> Adding error handling to onReponse interceptor and formatting

- mlte/frontend/nuxt-app/pages/negotiation-card.vue
I added some additional text to the System Requirements section to make it easier for people to understand QA scenarios.
> Changes to Negotation Card to provide better guidance for scenarios

- mlte/frontend/nuxt-app/pages/negotiation-card.vue
Updates the negotiation card instructions. @sei-aderr, I wasn't completely sure if I needed to do any further formatting with the addition of bullets in this section so let me know if I need to change it. Thanks!
> Update Negotiation Card Instructions

- docs/docs/using_mlte.md
Updated documentation code snippets to match the demo code, in particular that they use the Oxford flower dataset (not the Iris one).
> Update Documentation to be Consistent with Demos

- .bumpversion.cfg
- Makefile
- README.md
- build.sh
- docs/docs/development.md
- docs/docs/index.md
- mlte/frontend/nuxt-app/package.json
- pyproject.toml
Bumping version to 1.0.2 to release new fixes, mostly from #562 . Also includes minor update to make/docs with make commands for frontend linting/type checking (not yet integrated).
> Release 1.0.2

- docker/Dockerfile.mlte
- docker/build.sh
- docker/deployment/compose_envs.sh
- docker/deployment/rebuild_and_restart.sh
- docker/deployment/start.sh
- Added isolated and version-pinned installation of Poetry
- Added error stops on scripts so that failure to build one container stops the whole process clearly
> Docker Improvements

- Makefile
- docs/docs/development.md
Makefile: added commands for venv and frontend env setup, to make it easier o create/recreate/refresh them. 
Addresses #669.
> Makefile Env Commands

- .bumpversion.cfg
- README.md
- docs/docs/index.md
- mlte/frontend/nuxt-app/package.json
- pyproject.toml
Preparing version 2.2.0 for release.
> Updating version to 2.2.0

- demo/readme.md
- demo/readme.txt
- demo/scenarios/1_requirements.ipynb
- docs/docs/development.md
- poetry.lock
- pyproject.toml
Fixes #723 by properly calling the store setup script. Also updates some docs related to the demo for clarity.
> Fix Scenarios demo store setup
